# Uncomment this line to define a global platform for your project
  platform :ios, '9.0'

target 'WBSwift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'SnapKit', '~> 0.22.0’
  pod 'MJRefresh'
end
